// i2cdef.h
#ifndef I2CDEF_H
#define I2CDEF_H

#define AVRI2C_M_START_SENT 0x08
#define AVRI2C_M_REP_START_SENT 0x10
#define AVRI2C_M_SLA_W_SENT_AND_ACKED 0x18
#define AVRI2C_M_SLA_W_SENT_AND_NACKED 0x20
#define AVRI2C_M_DATA_SENT_AND_ACKED 0x28
#define AVRI2C_M_DATA_SENT_AND_NACKED 0x30
#define AVRI2C_M_ARBITRATION_LOST 0x38
#define AVRI2C_M_SLA_R_SENT_AND_ACKED 0x40
#define AVRI2C_M_SLA_R_SENT_AND_NACKED 0x48
#define AVRI2C_M_DATA_RECEIVED_AND_ACKED 0x50
#define AVRI2C_M_DATA_RECEIVED_AND_NACKED 0x58

#define AVRI2C_S_RECEIVED_SLA_W_AND_ACKED 0x60
#define AVRI2C_S_ARB_LOST_AND_ACKED_OWN_SLA_W 0x68
#define AVRI2C_S_GC_RECEIVED_AND_ACKED 0x70
#define AVRI2C_S_ARB_LOST_AND_ACKED_GC 0x78
#define AVRI2C_S_DATA_RECEIVED_AND_ACKED 0x80
#define AVRI2C_S_DATA_RECEIVED_AND_NACKED 0x88
#define AVRI2C_S_GC_DATA_RECEIVED_AND_ACKED 0x90
#define AVRI2C_S_GC_DATA_RECEIVED_AND_NACKED 0x98
#define AVRI2C_S_RECEIVED_STOP_OR_REP_START 0xA0
#define AVRI2C_S_RECEIVED_SLA_R_AND_ACKED 0xA8
#define AVRI2C_S_ARB_LOST_AND_ACKED_OWN_SLA_R 0xB0
#define AVRI2C_S_DATA_SENT_AND_ACKED 0xB8
#define AVRI2C_S_DATA_SENT_AND_NACKED 0xC0
#define AVRI2C_S_LAST_DATA_SENT_AND_ACKED 0xC8

#define I2C_MASTER_TYPE_THRESHOLD 0x10
#define I2C_MASTER_BUFSIZE 32
#define I2C_MAX_DEVCOUNT 20

#define I2C_ERR_DEVOVF 1
#define I2C_ERR_UNHANDLED_STATE 2

#define I2C_MASTER_CMD_QUERY 0x42

#define AVRI2C_ERROR 0x00
#define AVRI2C_NOTHING 0xF8

// i2c statemachine
#define I2CSTATE_IDLE 0
#define I2CSTATE_ERROR 0xFF
#define I2CSTATE_DEVQUERY0 1
#define I2CSTATE_DEVQUERY1 16
#define I2CSTATE_DEVQUERY2 17
#define I2CSTATE_DEVQUERY3 18
#define I2CSTATE_DEVQUERY4 19
#define I2CSTATE_DEVQUERY5 20
#define I2CSTATE_DEVQUERY6 21
#define I2CSTATE_DEVQUERY8 22
#define I2CSTATE_DEVQUERY9 23
#define I2CSTATE_DEVQUERY10 24
#define I2CSTATE_DEVQUERY11 25
#define I2CSTATE_DEVQUERY12 26

#define I2CSTATE_SD0 2
#define I2CSTATE_SD1 27
#define I2CSTATE_SD2 28
#define I2CSTATE_SD3 29



#endif  // I2CDEF_H
